# Stolen from http://conda.pydata.org/docs/travis.html
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  # - "3.4"
  # - "3.5"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels bioconda
  - conda config --add channels r
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION joblib numpy scipy pandas pytest pytest-cov rpy2 bioconductor-iranges bioconductor-biocgenerics bioconductor-genomicranges r natsort
  - source activate test-environment
  - python setup.py install
  - pip install bx-python
  - python --version
  - python -c 'import pandas as pd; print(pd.__version__)'
  - ls tests
  - ls -latrh examples

script: python -m pytest --cov=triform tests

after_success: coveralls